version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    command: ["postgres", "-c", "listen_addresses=*"]

  sync-app:
    build: .
    container_name: sync-app
    restart: always
    depends_on:
      - postgres
    environment:
      MONGO_URI: "mongodb://mongo:27017/tdrive"
      PG_URI: "postgresql://user:password@postgres:5432/tdrive"
      PG_ADMIN_URI: "postgresql://user:password@postgres:5432/postgres"
      PG_DB: "tdrive"
    networks:
      - app_network
      - mongo_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
  mongo_network:
    external: true
